### ISSUE TITLE
时段组件显示当前投放时间文本有时候不显示

### ISSUE THREAD

**Issue by wuhy** [ecomfe/esui#271]
见下图红色框出来部分，一开始取消中间一个时段，是显示14:00-24:00，mouseover一下就突然消失了。。

![image](https://cloud.githubusercontent.com/assets/116542/2840287/bb29aa4a-d052-11e3-9316-745dec540618.png)

**Comment by yankun01** [comment]
当鼠标从外边缘移出移进之后会有这样的问题。 这个问题已经修好了。
