### ISSUE TITLE
IE10下Textbox的placeholder的默认样式有问题

### ISSUE THREAD

**Issue by hadesdu** [ecomfe/esui#278]
![image](https://cloud.githubusercontent.com/assets/2051247/2914403/7b83855c-d69a-11e3-8a32-e8600a894185.png)
默认状态下就是上图这样

![image](https://cloud.githubusercontent.com/assets/2051247/2914412/919d0fe8-d69a-11e3-8c9a-461b9f1bab11.png)
添加一行样式可以解决这个问题

**Comment by yankun01** [comment]
修改了样式。

**Comment by Justineo** [comment]
est 里面有 `.placeholder(#999)` 可用。
