### ISSUE TITLE
InputControl 增加 hideValidity方法

### ISSUE THREAD

**Issue by markfan** [ecomfe/esui#288]
hideValidity与 showValidity对应，用与隐藏验证信息

**Comment by Justineo** [comment]
再 mention 一下这个，我觉得这个还是必要的，否则每次调用就是类似这样的代码：

```js
var Validity = require('esui/validator/Validity');
var ValidityState = require('esui/validator/ValidityState');

var validity = new Validity();
var state = new ValidityState(true, '');
validity.addState('', state);
control.showValidity(validity);
```

有空我们发个 PR 也行~

**Comment by leeight** [comment]
+1

**Comment by chestnutchen** [comment]
+1

**Comment by otakustay** [comment]
嗯，好，等PR

**Comment by chestnutchen** [comment]
后来发现只要两句
```javascript
            /**
             * 隐藏验证信息
             */
            hideValidity: function () {
                var validity = new Validity();
                this.showValidity(validity);
            },
```
不过语义清晰一点，放到Toast的pr里边一起了？

**Comment by otakustay** [comment]
嗯，放那边一起吧



Best regards

Gray Zhang



在 2015年1月16日 下午2:53:31, chestnut (notifications@github.com) 写到:

后来发现只要两句

            /**
             * 隐藏验证信息
             */
            hideValidity: function () {
                var validity = new Validity();
                this.showValidity(validity);
            },
不过语义清晰一点，放到Toast的pr里边一起了？
