### ISSUE TITLE
是否可以将type="submit"的Button升级为InputControl

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/esui#319]
两种原生的case
1. `<input>`标签使用`type="submit"`，并且有`name`属性和`value`值，提交表单时会将该`input`的`value`一起提交
2. `<button>`标签使用`type="submit"`，并且有`name`属性和`value`值，提交表单时会将该`button`的`value`一起提交

现在的`Button`控件不是一个`InputControl`，无法做到这种效果。

**Comment by yankun01** [comment]
解决了，就关了啊。
