### ISSUE TITLE
table的setData()的表现跟setProperties{datasource:**}表现不一致

### ISSUE THREAD

**Issue by yanlingling** [ecomfe/esui#336]
table的setData()的表现跟setProperties{datasource:**}表现不一致，前者会重置selectedIndexMap,表格内容更新后，选择是没有的。后者没有，会导致表格内容更新后，勾选还在。
内容更新后，勾选不在更合理一些。

**Comment by yankun01** [comment]
加了一个参数。 可以通过参数控制是否需要重置选项。 默认行为和原来保持一致。
