### ISSUE TITLE
table控件所在容器width小于table所有列宽度和时，table显示异常

### ISSUE THREAD

**Issue by yanghuabei** [ecomfe/esui#338]
@wurongyao 

table显示异常截图：

![20140814165002](https://cloud.githubusercontent.com/assets/6822885/3917806/02a0ca06-2392-11e4-8b30-3309809116b6.jpg)

我看了一下table的代码，发现table的`head`和`body`容器的宽度被设置为table的宽度，并且`body`被设置了`overflow-x:hidden`，导致超出table宽度的`head`和`body`没有`background`和`border`。
我觉得更合理的计算`table.head, table.body`宽度的方式是自适应内容宽度或者：
```
    if (table.realWidth > table.colWidth) {
        table.body.style.width = table.realWidth;
        table.head.style.width = table.realWidth;
    }
    else {
        table.body.style.width = table.colWidth;
        table.head.style.width = table.colWidth;        
    }
```

我们的项目有这样一个需求：当table的列过多时，给table加横向滚动条。
使用现在的table控件，实现这个功能需要override `body`和`head`容器自适应内部元素的宽度，写一些感觉不是很必要的css。

不知道table能否支持横向滚动条，虽然横向滚动很变态。如果`body`和`head`的是自适应内部元素的，横向滚动只需设置table的`overflow-x`就ok了。

**Comment by Phinome** [comment]
@yanghuabei 我也遇到这个问题了，原因就是你描述的那样，后来，找了个可能比较笨的方法，给 table 配置一个较大的 width 属性值。

``` javascript
'List': {
                    width: 1600,
                    columnResizable: 1,
                    followHead: 1,
                    datasource: '*list',
                    fields: '*fields',
                    editable: true,
                    select: "multi",
                    noDataHtml: '<div class="ui-table-null">暂无数据</div>'
                }
```

这样就不走动态计算 table width 的逻辑了。
然后，横向滚动就有了。
