### ISSUE TITLE
ESUI依赖的问题？

### ISSUE THREAD

**Issue by Phinome** [ecomfe/esui#346]
想使用 ESUI 和 ER ，但看现在的代码结构和更新趋势，貌似都要采用 EDP 作为构建平台，请问后续有无计划开源一个纯净的框架呢？谢谢！

还有一个问题，关于 ER 和 ESUI 目前是作为一个内部项目在迭代还是计划作为一个开源项目呢？如果作为开源项目，那么上面的问题希望能得到解答，如果不是，那上面的问题就显得没有意义。

**Comment by yankun01** [comment]
现在在用edp import esui 既可以全部导入所有的依赖。
