### ISSUE TITLE
CommandMenu 和 Button 的默认样式不太一致

### ISSUE THREAD

**Issue by leeight** [ecomfe/esui#377]
![image](https://cloud.githubusercontent.com/assets/104052/4601962/5f64e992-511f-11e4-9212-8e17aed9e450.png)

padding和border-radius

**Comment by yankun01** [comment]
https://github.com/ecomfe/esui/releases/tag/3.2.0-beta.1
版本应该已经解决了这个问题。

**Comment by otakustay** [comment]
对于一些系统升级3.2.0的成本确实比较高的，对于BUG类的我们在3.1上也同样维护修复吧

@leeight 这个问题你还需要吗……其实我觉得不是什么大问题

**Comment by leeight** [comment]
不用了，我们自己调整了。另外升级到 3.2 估计短期不太容易搞

**Comment by yankun01** [comment]
@leeight @otakustay 3.1 - dev分支已经修改。
