### ISSUE TITLE
ControlCollection上调用dispose遇到的问题

### ISSUE THREAD

**Issue by hanbf** [ecomfe/esui#395]
ControlCollection上调用各类方法用的代码是，
                    var result = this.invoke.apply(this, args);
这里要循环this然后调方法。
如果方法要修改ControlCollection的话，就会出问题。比如dispose。
dispose会把控件从所在的group里挪掉，此时这个group正在被循环，挪掉改变了group数组，于是。。

**Comment by zxhfighter** [comment]
`var args = [this];` 和 `var args = [].slice.call(this);` 并不等价，调用 ControlColeection 的 show 方法时会出现问题，应该修改成 `var args = [u.clone(this)];`
