### ISSUE TITLE
从master移除标准化相关内容

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#397]
esf和eicons没准备好，现在的情况是esui的master完全不能用

需要从master移除最近的几次pull request，发布一个独立版本，把这几个pull request的内容移到measures-2nd分支上去，后续再合并回master

**Comment by otakustay** [comment]
上面master应该是3.1.0-dev

看了下，东西很多，最好这样：

1. 把 b356d0bdb06d4a1b726cf876896ca9cf295e8968 之后的东西，全部cherry pick到measures-2nd上去
2. 把 b356d0bdb06d4a1b726cf876896ca9cf295e8968 之后的，几个修BUG的和measures-2nd无关的东西，cherry pick到另一个随便啥分支foo去
3. 回滚至 b356d0bdb06d4a1b726cf876896ca9cf295e8968
4. merge foo
5. 再发布新版本

有点折腾…… @yankun01 @Justineo

**Comment by Justineo** [comment]
已搞
