### ISSUE TITLE
helper/event中有一处不安全的数组操作

### ISSUE THREAD

**Issue by jianling** [ecomfe/esui#406]
在 *[helper/event](https://github.com/ecomfe/esui/blob/master/src/helper/event.js#L128)* 中的 `removeGlobalDOMEvent` 有一处对 `pool[type]` 的 `splice` 操作

而 `removeGlobalDOMEvent` 会在 `triggerGlobalDOMEvent` 方法中间接调用到

这样就导致 `pool[type]` 在被 `triggerGlobalDOMEvent` 执行 `each` 操作的过程中，被 `removeGlobalDOMEvent` 改变，从而报错。

这个问题在 esui + underscore1.5.2 时不会出现，underscore 升级到 1.7.0 就出现了。

因为 underscore1.5.2 中的 [each](https://github.com/jashkenas/underscore/blob/1.5.2/underscore.js#L79) 方法使用了原生的 `forEach`，但在 [1.7.0](https://github.com/jashkenas/underscore/blob/1.7.0/underscore.js#L97) 中又[放弃](https://github.com/jashkenas/underscore/pull/1525)使用 `forEach` 了，改用 for 循环实现；原生 forEach 在遇到数组被 splice 时只会退出执行，for 循环则会报错。

**Comment by leeight** [comment]
+1

**Comment by otakustay** [comment]
Plz review

**Comment by leeight** [comment]
:100:
