### ISSUE TITLE
可否去掉Layer对自身的mousedown事件stopPropagation？

### ISSUE THREAD

**Issue by wanghaihan** [ecomfe/esui#407]
Layer的getElement方法中：
                this.control.helper.addDOMEvent(
                    document, 'mousedown', u.bind(close, this));
                // 不能点层自己也关掉，所以阻止冒泡到`document`
                this.control.helper.addDOMEvent(
                    element,
                    'mousedown',
                    function (e) { e.stopPropagation(); }
                );
我看到在close方法中，已经处理了target或者target的parents里是自身，则不执行关闭操作。那么何必再stopPropagation自身的monsedown？
如果不去掉这里，就会导致其他控件无法给Layer 应用monsedown事件。例如：layer中有个selector，selector的下拉框也是layer，它注册了document的monsedown以达到点击除自身之外的任何地方都收起下拉框。但是现在的layer实现就会导致，用户点击layer区域，也都不会让selector的下拉框收起。

**Comment by otakustay** [comment]
如果去掉这个阻止冒泡的话，以你的场景为例：

```
- Layer
    - Select
        - SelectLayer
```

注意这里并没有DOM上的父子关系。如果在`SelectLayer`上点击，则`Layer`会被收起，因为从`SelectLayer`到`documentElement`一路上根本没有`Layer`这个东西

我觉得出现上面的情况会更糟糕……我点了个下拉框，整个`Select`就不见了，所以我宁可选择点`Layer`的时候`SelectLayer`没反应

不知道我的逻辑是不是对……

**Comment by wanghaihan** [comment]
多谢回复。
首先大Layer套小Layer有两种情况：
1.dom结构上存在父子关系：
这种情况下，点击小Layer时，事件冒泡会都触发大和小layer的事件，target都是subLayer。但是我们只需判断当前的target以及当前target的所有parents里是不是我们要关闭的layer即可。事实上，Layer的私有方法close已经做了这一步。这样，外层Layer不会被收起。
2.只是位置上看着被包含，其实没有真正的父子关系。
这种情况下，阻止小layer的事件冒泡确实可以防止不关闭其他layer的作用，但是这个是不是宁可错杀一千，不可放过一个的感觉。因为它相当于让layer永不冒泡monseclick事件。不仅仅是其位置下方的浮层layer，网页任何组件在document上注册的monseclick事件，在layer上都会失效。我的感觉是，对于一个公共容器来说，与其屏蔽掉monseclick，不如就让那些非要放弃dom的父子关系，而是通过各种绝对定位来模拟父子包含的那些人自己去处理这种隐藏的逻辑。因为位置，事件等等，这本身就是属于它模拟父子关系的一部分。
再不济，是不是也可以通过检测mouse的postion是否处于当前layer的范围来实现阻止隐藏。

我来说一下我提这个issue的起源：我们的系统里会同时使用rangecalendar和calendar。rangecalender是自己写的layer，因此，当打开了选年月的下拉框，点击rangecalendar其他地方，就会自动收起年月下拉框。但是calendar控件由于是使用的layer组件，点击calendar中的其他地方，不会自动收起年月下拉框。这种体验不一致的行为给我们造成了很大的困扰~~~
希望大神帮忙解决~。

**Comment by yankun01** [comment]
3.2里面解决了。
