### ISSUE TITLE
TextBox设置data-ui-hint属性后，如果上层div隐藏，设置data-ui-width属性无效

### ISSUE THREAD

**Issue by wanglinfang2014** [ecomfe/esui#408]
TextBox设置data-ui-hint属性后，如果上层div隐藏，设置data-ui-width属性无效

**Comment by otakustay** [comment]
确实是无效的，并且我们不打算修复，这个的根源就是offsetWidth的计算在隐藏状态下是拿不到的，没有什么办法可以完美解决这问题



Best regards

Gray Zhang



在 2015年1月20日 上午10:58:13, wanglinfang2014 (notifications@github.com) 写到:

TextBox设置data-ui-hint属性后，如果上层div隐藏，设置data-ui-width属性无效
