### ISSUE TITLE
textinput在初始化之后应该去掉input元素的data-ui-type属性

### ISSUE THREAD

**Issue by jianling** [ecomfe/esui#409]
textinput初始化之后的DOM结构如下：
```html
<esui-text-box data-ui-type="TextBox" data-ui-mode="text" data-ui-placeholder="默认状态" data-ctrl-id="esui8785927" id="ctrl-text-box-esui8785927" data-ctrl-view-context="text-box" class="ui-ctrl ui-textbox">
    <input data-ui-type="TextBox" data-ui-mode="text" data-ui-placeholder="默认状态" id="ctrl-text-box-esui8785927-input" placeholder="默认状态" style="width: 200px;">
</esui-text-box>
```

input 元素仍然带有 `data-ui-type` 属性，但是没有 `data-ctrl-id` 属性，这样如果因为某些原因，再次调用main.init方法的时候，就会被认为是一个新的控件去初始化。

**Comment by otakustay** [comment]
最新开发分支已经修复此问题，修改了replaceMain方法去掉所有ui属性

**Comment by Justineo** [comment]
已搞

**Comment by Justineo** [comment]
@otakustay 

https://github.com/ecomfe/esui/commit/4f0d262544c845015a1db6d6862efe002260d589#diff-93e62f6df190164970efdd1e30d2ea72L349

**Comment by otakustay** [comment]
已经同步到`3.1.0-dev`了，现在我的系统在升级到dev分支，基本测一下后我争取本周会有个新版本
