### ISSUE TITLE
RangeCalendar点击取消按钮后对选中日期的样式没有处理

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/esui#410]
![image](https://cloud.githubusercontent.com/assets/2787987/5934524/8ca68cc0-a70b-11e4-818c-462b5844777e.png)

正在看

**Comment by Justineo** [comment]
@DDDBear 看一下？似乎代码没改过，是不是受最近 Layer 改动影响了？

**Comment by DDDBear** [comment]
这是咋选出来的？哪个分支上的？

**Comment by chestnutchen** [comment]
只要取消了继续就这样了，取消后样式没重置，还在选的那个上边。3.1.0-beta.6

**Comment by otakustay** [comment]
用最新的`3.1.0-dev`再试一下？

**Comment by chestnutchen** [comment]
拷了个`MonthView`用用，看起来可以了

**Comment by otakustay** [comment]
好，我先close，有问题再开，一行代码的血案……

**Comment by chestnutchen** [comment]
一开始还想pr，找了好久没找到，项目紧就没追。。。
