### ISSUE TITLE
TipLayer 未处理 `attachTo` 指向的元素的事件销毁

### ISSUE THREAD

**Issue by Justineo** [ecomfe/esui#411]
比如 `showMode` 为 `over` 时会对 `targetDOM` 绑定 `mouseover` 事件，`dispose` 时或 `attachTo` 另一元素时老的事件似乎没有清除。

**Comment by chestnutchen** [comment]
然后页面就很卡。TipLayer最好还是记住它依附的元素吧。。

**Comment by DDDBear** [comment]
看了下，之前确实没有考虑在attach的时候把之前的绑在layer上的事件清掉。所以这次做了一个修正，把layer上的事件绑定扔在delayShow执行的时候，并且在绑定之前，删除附在上面的所有其它绑定。

但是绑在指向元素上的事件不能在每次重新attach的时候就解绑，因为“二次attachTo“当时的设计初衷是，一个layer可以被多个目标共用，而不是一个用完了就不再用了。

我把代码提交上来，@Justineo 看看有没有解决现在的问题。

**Comment by Justineo** [comment]
@DDDBear 好吧，我们的使用场景是这样的：
搞了一个 Extension，可以放在任意控件上，鼠标移到内部任何带有 `data-title` 属性的元素上时，会显示一个对应的 Tip。之前因为 `despose` 有问题，所以使用方式是第一次创建完以后移到别的元素上就调用 `setContent` 并且 `attachTo` 新的元素。由于首次移入时给 `targetDOM` 绑定的 `mouseover` 事件还在，所以后面就不能正常工作了，而且会造成事件绑定的堆积。可能需要换成每次都 `dispose` 才能解决了。
话说之前和你讨论过的，目前的几个 `mode` 其实我们都不想要，这个场景下需要的是「初始化时自动显示且不响应交互事件」。
