### ISSUE TITLE
Control.js setProperties的问题

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#427]
setProperties 这段代码为什么不直接用var oldValue = this.get(key), 而且和get里的getterMethodName不一致（多了'Property'）

setProperties
============================================
                       var getterMethodName =
                            'get' + lib.pascalize(key) + 'Property';
                        var oldValue = this[getterMethodName]
                            ? this[getterMethodName]()
                            : this[key];
get
============================================
            get: function (name) {
                var method = this['get' + lib.pascalize(name)];

                if (typeof method == 'function') {
                    return method.call(this);
                }

                return this[name];
            },

**Comment by otakustay** [comment]
`getXxxProperty`用于在`setProperties`时获取一个旧值与新值比较，而`getXxx`用于供外部调用获取值

新旧值的比较有时候是控件的内部逻辑，逻辑与直接获取值比较有所不同，因此在某个时期我们提供`getXxxProperty`来“部分重写”新旧值比较的逻辑

在后续的发展中，我们发现这种“部分重写”并不是一个完善的方案，因此进一步提供了`isPropertyChanged`这个方法来提供“完全重写”新旧值比较的可能性。而`getXxxProperty`这种方法作为向后兼容而被保留了下来，在当前的情况下其实并没有什么用

**Comment by uraincay** [comment]
明白，谢。
