### ISSUE TITLE
Link.js 中 initOptions的问题，为什么不是this.setProperties(...)

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#428]
这里用到u.extend(this, properties);有什么特殊原因吗？
像viewContext这类特殊的property，这样就没有viewContext.add, 以后viewContext.get()就拿不到控件了。

Link.js
===============================         
   initOptions: function (options) {
        ...
        u.extend(this, properties);
   },

**Comment by otakustay** [comment]
这就是一个by design的实现，`viewContext`就是允许作为控件的初始化参数传入的，用来指定该控件属于哪一个`ViewContext`，你说的`get()`获取不到是怎么样的情况，是否可以提供一个示例的代码？

在`initOptions`之后会有一个叫`initViewContext`的过程，使用`this.viewContext`自动调用`add`等操作完成控件与`ViewContext`的关联

**Comment by uraincay** [comment]
再试了一次，是我搞错了。的确是在initViewContext的过程中初始化的。用了viewContext.get('domId'),而不是viewContext.get('controlId')。所以结果是undefined。sorry。

再问一个相关的问题。我看到
Button.prototype.initOptions最后一句是this.setProperties(properties);
而
Label.prototype.initOptions最后一句是u.extend(this, properties);

setProperties中也有setViewContext调用，也就是说初始化过程中setViewContext被调用了两次（当然所有相关方法都有===判断保护, 相关调用方法在开始就返回了）。

我的问题是：
假设我自己写个控件，推荐的做法是哪种呢？this.setProperties(properties);还是u.extend(this, properties);？

**Comment by otakustay** [comment]
推荐使用`setProperties`，因为你的子类可能通过重写该方法实现一些自定义的逻辑

部分控件直接使用了`u.extends`更多是代码没写好的因素，考虑到`Link`这类的也不会有子类，所以本着不出问题不改的原则就放那了

**Comment by uraincay** [comment]
明白，谢谢解答。
