### ISSUE TITLE
control.styleType是不是类似TextBox.mode的功能？

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#430]
整个库的控件都没用到styleType(helper/dom中有控制classes的逻辑)，我想知道这个属性当时是怎么设计的，是类似TextBox.mode的功能吗？他和mode之间表达的意思有啥区别么？

**Comment by otakustay** [comment]
`styleType`的功能是生成class，因为有时候你要写个控件的子类，但其实样式上不会有什么变化，所以要用父类的class

而`esui`自身并没有什么控件的继承层级，类似`InputControl -> TextBox`的也和样式无关，所以从`esui`本身来看确实没有用到

我举个例子：你要写一个`GroupSelect`，在下拉框的基础上增加分组功能。此时你又想要`Select`控件原本的箭头啊之类的样式，所以你会写`type = 'GroupSelect'; styleType = 'Select'`

这个属性和`mode`并不相同，区别在于：

1. `mode`是除class外，也与其它逻辑和属性相关的，比如影响到`<input>`元素的`type`属性，而`styleType`是个纯样式
2. `styleType`与`type`相同，是跟着控件类型走的，即不允许用户在创建时设置别的值，因此是`readonly`的属性，而`mode`显然是一个可配置项

**Comment by uraincay** [comment]
谢快速回复。

我以为styleType是为了区分同一控件下不同mode用的，既可以用来控制样式，又可以影响main的属性。

这是我的一些不同意见：
1.type = 'GroupSelect'; styleType = 'Select'
如果这么写的话，那么main的class里就不会有ui-GroupSelect之类了，因为styleType的优先级会高于type.

参考helper/dom
=======================================
        function getControlClassType(control) {
            var type = control.styleType || control.type;
            return type.toLowerCase();
        }


2.mode是除class外...
在TextBox中，mode是和class无关的。我设置的三种不同的mode,所有main的class都是"ui-ctrl ui-textbox",也就是说三者之间的样式无法区分了。因为这样，TextBox再造了个targetType属性，往Validity里面塞。
src/Validity  getClasses
==========================
            if (target || label.targetType) {
                var targetContext = {
                    type: label.targetType || target.type,
                    skin: target && target.skin
                };
                targetHelper = new Helper(targetContext);
            }

**Comment by otakustay** [comment]
1. 没错，样式上完全就是与基类相同的了，具体你可以参考这个控件，是个典型的应用：https://github.com/ecomfe/ef/blob/master/src/ActionDialog.js

    如果有些场景需要子类和父类都有class标识，需要子类自己加额外逻辑实现。现在没有遇到类似的需求，如果此类需求较多的话我们会考虑增加相关的逻辑

2. 嗯……毕竟太久了我也没记清。`mode`应该确实和class无关，原因是没有这个的需求，且`mode`是`TextBox`特有的，不能用于作为一个接口

**Comment by uraincay** [comment]
我没相关需求，只是碰到不明白的就来问你。谢解答。
