### ISSUE TITLE
string/lib.camelize错误

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#431]
lib.camelize('aaa-jjj') // aaa-Jjj
是不是应该是aaaJjj?
===================
目测function参数应该是function(match, alpha)

**Comment by otakustay** [comment]
嗯，这函数就是指定了几个分隔符，如果遇到额外的分割符再给加上去，一直是这么在玩……

你可以发一个PR来，目标分支为3.1.0-dev



Best regards

Gray Zhang



在 2015年3月6日 下午9:09:29, uraincay (notifications@github.com) 写到:

lib.camelize('aaa-jjj') // aaa-Jjj

是不是应该是aaaJjj?

目测function参数应该是function(match, alpha)
