### ISSUE TITLE
lib.insertAfter的问题，当parent.lastChild == reference时会有错误

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#433]
lib.insertAfter = function (element, reference) {
            var parent = reference.parentNode;

            if (parent) {
                parent.insertBefore(element, reference.nextSibling);
            }
            return element;
        };

**Comment by uraincay** [comment]
在chome上试了一把，parent.insertBefore(element, null)效果等同appendChild, 不知道其他浏览器是否都兼容

**Comment by Justineo** [comment]
我记得这个问题我之前好像也提过……

http://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/core.html#ID-952280727

> If refChild is null, insert newChild at the end of the list of children.

**Comment by uraincay** [comment]
close。确保没问题就好。
