### ISSUE TITLE
Control.removeChild 的问题

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#435]
为什么不把child control从parent control的viewContext里删除？

**Comment by otakustay** [comment]
我想了很久，确实应该移掉的……我回头会改一下



Best regards

Gray Zhang



在 2015年3月8日 上午1:23:02, uraincay (notifications@github.com) 写到:

为什么不把child control从parent control的viewContext里删除？

**Comment by Justineo** [comment]
想了很久肯定是怕自己在当时有什么特别的设计吧哈哈。

**Comment by yankun01** [comment]
在`addChild`的时候，首先添加了child control的和当前control的父子关系。 如果所要添加的child control的ViewContext和当前control不一致，会把child control从老的ViewContext中移动到和当前control相同的ViewContext中去。

在`removeChild`的时候，现在仅仅是移除了当前control和child control的父子关系。 ViewContext并没有做处理。 

这里的逻辑是这样的，当一个control初始化的时候会被添加到一个ViewContext。仅仅在组件`dispose`的时候会从ViewContext中移除。removeChild移除了一种关系，并没有导致child的`dispose`。因此如果需要从ViewContext中移除，在`removeChild`之后调用一下`dispose`方法即可。

这也是之前和@otakustay讨论的结论，这个暂时关掉了。
