### ISSUE TITLE
TipLayer去掉了mouseout触发hide的功能？

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/esui#439]
b581a3407d87c5a799cb6ac57809276d66cd5a9f

在 `showMode` 为 `over` 时，鼠标移出也不会隐藏浮层。

**Comment by otakustay** [comment]
@DDDBear `TipLayer`现在啥状态，我感觉有点乱唉……

**Comment by QuantBull** [comment]
未能复现哈。有例子么。

**Comment by chestnutchen** [comment]
不是在3.1.0修复了么 -    -

**Comment by yankun01** [comment]
那就关了吧
