### ISSUE TITLE
Pager 在不设置PageSizes 是，总页数计算错误

### ISSUE THREAD

**Issue by tangguangyao** [ecomfe/esui#441]
pager 源码 501行

// 同步一次状态
changePageSize.call(this);

执行changePageSize

如果没有设置PageSizes
var pageSize = parseInt(this.getChild('select').getValue(), 10);
this.pageSize = pageSize;
this.pageSize变为 NAN

需要将changePageSize.call(this); 放在第二个分支执行，而不是全部都同步

**Comment by yankun01** [comment]
@tangguangyao let me see it.

**Comment by QuantBull** [comment]
的确如此 后续会修复
