### ISSUE TITLE
麻烦把main.less编辑后的css文件放在demo中

### ISSUE THREAD

**Issue by mulong** [ecomfe/esui#444]
麻烦把main.less编辑后的css文件放在demo中，我用下载的less生成css时一直报错！没办法看demo效果

**Comment by mulong** [comment]
你们自己有没有试下载后看demo，引用好多js都没有放到统一文件夹中，demo根本就没办法运行！

**Comment by Exodia** [comment]
- -额，，这个主要原因是我们的 demo 是运行在 edp 环境下的，会自动把 less 转成 css；
确实在每次发布前统一编译下 main.less，这样跑 demo方便些，不用开 edp 。 @otakustay

**Comment by yankun01** [comment]
https://github.com/ecomfe/esui/releases/tag/3.2.0-beta.1

新版本中已经可以直接运行demo了。
