### ISSUE TITLE
esui库中引用jquery和jquery UI

### ISSUE THREAD

**Issue by yankun01** [ecomfe/esui#459]
JQuery
好处
1. ESUI代码不用处理CSS操作和Event模型
2. 迁移现有社区JQuery组件相对容易
3. 浏览器兼容代码委托到JQuery， ESUI代码集中在交互和需求上

缺点
1. JQuery min大概有100k左右的大小。
2. 内部有实现Promise和Ajax，在开发程序的时候我们是否也要使用，我们现在ER中有ajax.js 和 单独Promise模型。
3. 目前看来我们用到sizzle的机会实际上不是很多。而它的体积也不小。

关于JQuery UI，打算利用其draggable, droppable, resizable, position这些行为库作为我们组件的基础。组件开发者无需重复关注这些常见的拖拽行为。

好处
1. 行为库作为组件的基础，无需重复开发。
2. JQuery UI行为库稳定，扩展性不错，可以保证组件行为的正确性。
3. 利用现有行为，降低组件开发难度。

缺点
1. JQuery UI自己有独立的widget factory体系和生命周期。这和我们ESUI自己的生命周期管理上有一些重复。

说一下我个人的感觉， 个人感觉如果将来我们组件库要做的更稳定，开发简单。引用JQuery和一个稳定的行为库（JQuery UI draggable等）非常重要。 这可以让我们把精力集中在要解决的业务组件需求上，而不用解决为啥这个浏览器getcomputedstyle又不对了这种问题。提高组件开发效率。

大家一起讨论一下吧。

**Comment by leeight** [comment]
貌似不需要那么多API吧，esui/lib 不是已经马马虎虎够用了么？

**Comment by otakustay** [comment]
我和 @Justineo 讨论了一下，首先引入`jQuery`确实能解决一些问题，但其中会多出一些我们不需要的功能，从洁癖的角度来看这是很不爽的

所以有一个方案是这样的：
1. 在`esui`下放一个自定义的`jQuery`，比如`src/lib/jquery-esui.js`
2. 如果你的项目反正也要`jQuery`，或者你不关心多出来的那些功能，那么按正常使用，无视上面这个文件
3. 如果你不用`jQuery`，并且也不想要一个这么大的`jQuery`，那么在`require.config`里通过`map`进行配置，让`esui`下的`jquery`指向自带的那个`jquery-esui.js`就好了

用以下命令可以定制出1.11版的适合esui的：

``` sh
git co 1.11-stable
grunt custom:-sizzle,-ajax,-deprecated,-effects,-event/alias,-wrap,-core/ready,-deferred,-exports/global
```

定制完后的大概157KB，UglifyJS压缩后55KB，Gzip后18KB

定制还是基于1.x版本，2.x版本兼容性不好

另外使用者也可以自己定制一个出来，用`map`来控制

**Comment by otakustay** [comment]
另外上面的自定义我把`effects`模块也去了，所以动画效果就没了，如果以后我们还需要动画效果且jQuery的`animate`正好是有用的，可以别去掉
