### ISSUE TITLE
main.getControlByDOM获取控件的时候，当ViewContext不存在controlId时候不一定返回null

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/esui#461]
main.getControlByDOM获取控件的时候，当ViewContext不存在controlId时候不一定返回null，不知道我理解的是否正确？即mail.js中这一句：return viewContext.get(controlId);有可能返回undefined？

**Comment by Justineo** [comment]
[ViewContext.js](https://github.com/ecomfe/esui/blob/319196d81f830a1d7d57fb3bdf9719547538e56b/src/ViewContext.js#L148-L156)：

``` js
        /**
         * 根据id获取视图环境
         *
         * @param {string} id 视图环境id
         * @static
         */
        ViewContext.get = function ( id ) {
            return pool[id] || null;
        };
```

**Comment by feibinyang** [comment]
嗯  我看错函数了。。。
