### ISSUE TITLE
RangeCalendar 的一个问题

### ISSUE THREAD

**Issue by Justineo** [ecomfe/esui#462]
![image](https://cloud.githubusercontent.com/assets/1726061/7451895/ed47b54a-f288-11e4-8beb-6e8dabf03fb2.png)

复现步骤：
1. 点击控件展开 MonthView 的浮层；
2. 点击年份/月份下拉菜单展开 Select 浮层；
3. 点击 MonthView 浮层右上角的关闭按钮，出现图中情况，Select 浮层没有关闭。

**Comment by otakustay** [comment]
这好像就是个N久以来的问题，因为所有的层都会把`mousedown`阻止冒泡，那么层类的控件有嵌套的话，就会有这问题……

如果在控件层面通过编码的方式控制这些是可以的，程序会复杂不少……

**Comment by yankun01** [comment]
是select的层没有被隐藏对吧。 把所有的layer放到body下的设计是由于layer在计算位置的时候不支持嵌套到子元素。后期优化select的layer之后就应该不会有这个问题了。 能想到一个办法就是在rangeCalendar关闭的时候去强制关闭一下select layer。

**Comment by yankun01** [comment]
``` js
                // 关闭layer的时候关闭select的layer
                // https://github.com/ecomfe/esui/issues/462
                // 当select layer可以嵌套到主元素之后可以把这个移除
                calendar.layer.on('hide', function (e) {
                    function hideSelectLayer(monthView) {
                        monthView.getChild('yearSel').layer.hide();
                        monthView.getChild('monthSel').layer.hide();
                    };
                    var tar = e.target.control;
                    hideSelectLayer(tar.getChild('beginCal'));
                    hideSelectLayer(tar.getChild('endCal'));
                });
```

尝试这样修复了一下，目前可以解决这个问题。

**Comment by yankun01** [comment]
https://github.com/ecomfe/esui/tree/3.1.0-dev
上修复了。
