### ISSUE TITLE
新增src/css/Layer.less的css important问题

### ISSUE THREAD

**Issue by cnlf** [ecomfe/esui#465]
文件：src/css/Layer.less

.@{ui-class-prefix}-layer-hidden {
    display: none !important;
}

由于!important的优先级高于行内样式，导致创建的Layer默认是隐藏状态，隐藏的元素导致Layer.attachTo里的var targetOffset = lib.getOffset(target);获取不了元素的位置信息。

**Comment by yankun01** [comment]
@wanlingfeng 是不是应该把hidden状态去掉之后再去取offset呢？
你遇到的问题是什么样子的。

**Comment by yankun01** [comment]
已经把这个important去掉了。 后续我会把所有用到的important的地方再review一下。 你可以从3.2-dev分支获取一下最新的build
