### ISSUE TITLE
ie8下，boxGroup 从 dom 节点获取 value 的 bug

### ISSUE THREAD

**Issue by Exodia** [ecomfe/esui#469]
问题代码为：if (box.getAttribute('checked') !== null) {
                        values.push(box.value);
                    }

ie8下未设置 checked 属性时, box.getAttriebute('checked') 我这测试demo是返回 false， 在项目中返回了空字符串，仅判断是否为 null 会导致 ie8下未选中的 radio值也被抽取为选中值

https://github.com/ecomfe/esui/blob/master/src/BoxGroup.js#L90

**Comment by yankun01** [comment]
@Exodia 
我看了一下最新dev分支的代码是

``` js
                    // 之前这里用了 getAttribute，在 ie8下，未设置 checked，返回的是空字符串，会导致逻辑问题
                    // if (box.getAttribute('checked') !== null) {
                    if (lib.hasAttribute(box, 'checked')) {
                        values.push(box.value);
                    }
```

不知道是不是已经解决了这个问题。

**Comment by Exodia** [comment]
- \- 额。。这好像是我很久之前修复的，估计一直没发布？

**Comment by yankun01** [comment]
前些日子我合并的一个pr里面的。 那3.2 beta.2中我们就可以用最新的了。 
你暂时先拉一下dev分支吧。
