### ISSUE TITLE
一套适用现有体系的扁平化主题

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#470]
现有的standard主题无法适用于任何一个系统，我们只能期望未来会有产品来使用

但现在我们比较急切地需要一套能适用于现有体系的theme，其特点应该包括：
1. 符合现有扁平化的设计，如圆角等效果应该去除
2. 更为精简的色盘
3. 整合已知的各种variants

我会统计SSP端已经UE/UI标准化的系统有多少色彩，直觉上我们的色盘应该只需要<=10个颜色就可以完成一整个系统

variants现有为止会包括“链接型按钮”、“下拉框型按钮”、“按钮型链接”等，也需要进一步整理

考虑到后续的银河、微购、特卖、新北斗都需要，这个事希望 @yankun01 和 @DDDBear 和 @Exodia 可以共同推进，6月能够完成是最好的

**Comment by yankun01** [comment]
UE他们还在后续整理一些设计。这次会一并加进去。

**Comment by otakustay** [comment]
我需要UE的设计确实是标准化的，希望有他们**明确的确认**

我对SSP系统进行了一下色彩的分析，一共用到了177种颜色，这是非常不正常的。经过进一步的整理，我发现可以使用7种彩色+7种灰色+黑+白+错误色+高亮色基本覆盖所有的需求，我建议各系统也可以看一下自己系统是怎么样的，可以使用工具：http://gitlab.baidu.com/shenbin01/css-color-analysis

如果仅仅是满足现有的系统的需求（假设这个系统的设计是标准化的），那么我们所谓的theme就只需要暴露20个左右的色彩变量就够了……

**Comment by yankun01** [comment]
http://ecomfe.github.io/esui-family/controls/index.html

跟UE协商修改过的版本，不能修改的也做了说明。目前UE正在进行二次review。 确认后就可以发布了。
