### ISSUE TITLE
CommandMenu 的一个小问题

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/esui#472]
在一行之内放置两个 CommandMenu ，第二个 CommandMenu 选中某一项，主元素中显示相应文本，然后两个 CommandMenu 水平方向上就对不齐了。

可以在[此处](http://yibuyisheng.github.io/esui-demo/demo/CommandMenu.html)重现这个问题。

**Comment by Justineo** [comment]
inline-block 元素的 baseline 位置的问题（[Visual formatting model details](http://www.w3.org/TR/CSS21/visudet.html#propdef-vertical-align) 最下面）：

> The baseline of an 'inline-block' is **the baseline of its last line box in the normal flow**, unless it has either no in-flow line boxes or if its 'overflow' property has a computed value other than 'visible', in which case the baseline is the **bottom margin edge**.

选中后有内容，baseline 由 line box 决定，无内容则为下外边距的边缘。

可以给元素默认添加一个零宽空格，不过这样会占用一个伪元素。可以再看看有没有更好的方法。

``` css
.ui-commandmenu:before {
    content: "\200b"; /* zero-width space */
}
```

**Comment by yankun01** [comment]
好像加一个vertical-align:middle就不错开了。

**Comment by yibuyisheng** [comment]
@yankun01 vertical-align:middle 似乎不能真正解决问题，注意看 @Justineo 介绍的关于基线对齐的原理。对于 vertical-align:middle ，《CSS 权威指南》中说：

> 将元素的行内框的垂直中点与父元素基线上 0.5ex 处的一点对齐。

我的理解是，第二个 CommandMenu 主元素塞入了文本之后，就会使行框有了“文本基线”（ baseline ），这个基线对于不同的 font-family 可能是不一样的。此时第一个 CommandMenu 还是一个 display:inline-block ，其内容区大小是元素的`固有尺寸＋内边距＋边框＋外边距`，浏览器要保证这个 CommandMenu 的内容区下边缘和基线对齐，于是就导致了我最开始说的现象。

如果对第一个 CommandMenu 使用 vertical-align:middle ，会让第一个 CommandMenu 内容区的垂直中点与行框基线上 0.5ex 处对齐，所以似乎并不能解决问题。

拙见，说的不对的，请指正！

**Comment by Justineo** [comment]
@yankun01 这两个是对齐了，但是这样就丧失了按 baseline 对齐的可能性了。

**Comment by yankun01** [comment]
理解了，我的方法有些太暴力了。 两个·div·的区别就是一个有内容，一个无内容。 按照@Justineo 说的，我们只能在其中一个里面加一个空格了， 如果非得要baseline对齐的话。 话说为啥非得要baseline对齐呢。

**Comment by yankun01** [comment]
@yibuyisheng 为啥一定要baseline对齐呢。

**Comment by yibuyisheng** [comment]
@yankun01 有其他更好的对齐方案？

**Comment by Exodia** [comment]
如果不baseline对齐，在 commandMenu 后还跟着其他内联文字的话，会影响文字的对齐吧？

**Comment by otakustay** [comment]
如果没有文本则直接写个空格进去就好了？也不用伪元素

**Comment by otakustay** [comment]
baseline的概念和黄金分割很像，文字就是按baseline对齐比较顺眼…

**Comment by Justineo** [comment]
> 如果没有文本则直接写个空格进去就好了？也不用伪元素

也可以吧。

**Comment by yankun01** [comment]
嗯，确实有这个问题。 好了，加个空格就解决问题了。 那就关了啊。
