### ISSUE TITLE
对 html 获取的 attribute 做 JSON.parse转化

### ISSUE THREAD

**Issue by Exodia** [ecomfe/esui#475]
目前从 html 中解析到的属性都未做 json 的转化，这在编写控件的时候不得不对一些类型做手动转化：如 number，bool 的转化，也会导致使用过程中的一些 side effect。

增加 JSON.parse这层转化后大概情况如下：

data-ui-prop="1" => options.prop = 1

data-ui-str="'str'" => options.str = 'str';

data-ui-bool="true" => options.bool = true;

好处是开发控件的过程会比较流畅和直线，不用去考虑从html 解析出的属性转化这个场景。
风险在于可能对有些控件不兼容，对原有控件的字符串类型属性也不兼容。

**Comment by otakustay** [comment]
因为esui号称兼容ie7，所以就做不了这个…

**Comment by yankun01** [comment]
这次我在整理JQ组件的时候和毛总讨论了这个问题。

看看这样是否可以接受。其他的属性还是按照string去parse。以下几种情况除外。

``` js
data-ui-prop="1" => options.prop = 1
data-ui-prop="1.1" => options.prop = 1.1
data-ui-prop="true" => options.prop = true
data-ui-prop="false" => options.prop = false
data-ui-prop=" 'false' " => options.prop = "false"
data-ui-prop=" 'true' " => options.prop = "true"
data-ui-prop=" '123 " => options.prop = "123"
```

**Comment by otakustay** [comment]
把`AttributeParser`独立出来一个组件，默认实现我们可以讨论，与`main`组合在一起

如果其它使用场合有需要，可以重写一个自己的`AttributeParser`与`main`进行组合使用

**Comment by yankun01** [comment]
可以自定义parser了。
