### ISSUE TITLE
helper/life.js的dispose方法，是否调整移除扩展的时机

### ISSUE THREAD

**Issue by bobshen** [ecomfe/esui#480]
生命周期初始化时，先初始化子控件，再激活扩展。

扩展激活时，可能对已有的子控件绑定事件。对应的，销毁扩展时，也会解绑事件。

如果按照现在的流程，在销毁扩展前，控件的子控件已经被销毁，`childrenIndex`已不存在，因此解绑事件依赖的子控件也无法被找到。

是否应该微调一下 `helper/life.js` 的 `dispose` 的执行流程？

**Comment by Exodia** [comment]
按我理解，子控件dispose 的时候，应该会把绑定在自身上的事件也解除了吧，所以似乎不需要扩展去解绑了？

**Comment by otakustay** [comment]
这个问题泛化一下是“扩展需要用子控件”的问题，而不仅仅是事件

我理解 @bobshen 的说法是对的，我们在创建控件时是：

```
创建父控件 - 创建子控件 - 添加子控件扩展 - 添加父控件扩展
```

所以销毁应该正好反着来

**Comment by yankun01** [comment]
嗯，我来看看这个问题吧。 看看如何解决。

**Comment by yankun01** [comment]
fixed in 3.1 dev branch
