### ISSUE TITLE
想增加一个Tip相关的扩展

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#483]
与北斗的同学沟通时，他们有这样的需求：

> 各种Tip，出现在各种控件中
> 1、Crumb中要有tip
> 2、TableCell中要有tip
> 3、按钮上要有tip
> 4、BoxGroup中某一项后面要有tip
> 5、Tab标签上要有tip
> 6、select拉下来的菜单，某项要有tip
> 就差浏览器标签上搞tip了

这个需求不能说是不合理的，我认为在技术可以优雅地支持的前提下可以提供

因此我希望有这样的一个扩展，其作用是：
1. 注册控件渲染完成的事件
2. 获取控件的`extraTips`属性（属性名起复杂点避免冲突），这个属性的结构为`{selector, title, content, placement}`的数组，各属性作为如名称所示，`selector`为可以通过`querySelector`找到的就行，`placement`的作用下面说
3. 根据这个属性生成`Tip`控件放在对应的元素上，根据`placement`的取值，为`outsideAfter`、`outsideBefore`、`insideAfter`、`insideBefore`之一，作用看名称就行

有了这个控件，我们可以在大部分的东西上放控件，但有几个问题：
1. 控件的DOM结构不能变，一变就会让`selector`失效，这个比较麻烦，但从技术上来说也只能妥协，`selector`写得好些也许还没啥问题
2. 不能在控件DOM改变时去添加`Tip`，只能在控件渲染完后应用一次，即不动态

我认为上面第2点是我们技术的底线，我有办法去支持动态性但并不想这么做，需求和技术要在一定程度上取得平衡

@beidoufe 你看是否合适

我们有很多需要在技术上是可以不破坏原有设计的优点的情况下支持的，但是我并不了解北斗的进展，在缺少沟通的情况下让北斗在有些事的实现上可能用了非常hard code的解决手段，未来我们可以加强问题的反馈的话，不少事可能可以做得更好

**Comment by Justineo** [comment]
我们做了个这样的：https://github.com/ecomfe/bat-ria/blob/master/src/ui/extension/QuickTip.js

**Comment by otakustay** [comment]
@Justineo 事实上我最开始有考虑过你们这样的实现方式，但我发现部分控件比如`Select`等是会毁掉原有的DOM结构自己造的，而另一些控件如`Table`根本不给你自己写DOM结构的机会，所以没办法依赖`data-title`这种自定义属性，只能由外部给一个属性与DOM进行merge操作

所以最后我的方案变成了基于`selector`来做，这样把“需要Tip的元素”和“控件的DOM结构”分离在2个地方，避免控件的逻辑导致扩展失效

**Comment by Justineo** [comment]
恩……听上去就是不能用 `style` 属性所以写单独的 CSS 文件来控制样式一样的逻辑……

**Comment by beidoufe** [comment]
@otakustay 
sorry…才看到，不知为啥没提示有人at我

你说的实现方式，隐约记得在你的TableTip Extension中能看到过雏形：cell中写`<div class="table-tip">提示</div>`，Table afterrender后querySelectorAll('.table-tip')，改写innerHTML，创建layer并attachTo

当时觉得这样实现比在每个view层enterDocument后table.initChildren优雅多了，于是我在北斗的 `2、TableCell中要有tip` 需求实现过程中借鉴了这种方式。
但期间遇到了这个问题 https://github.com/ecomfe/esui/issues/520
这是`注册控件渲染完成的事件`这个功能没有做到位，因为目前咱们控件repaint后重写了dom，但不会触发afterrender，也没fire事件，上面的 改写innerHTML，创建layer等就没法执行。

作为esui资深用户，个人而言最希望做成extension，原因比较浅显
干净：需要更新代码的增量小，基本不会对已经做好的东西产生啥影响
灵活：能有丰富的配置项供选择（相比于集成在控件内部而言，例如Table内集成的表头tip，只能在文案左边）。当然这点是我的臆测，我总感觉如果tip继承在控件里，开发者就会忌惮这个控件的代码量而对tip进行减配…

多谢~
