### ISSUE TITLE
TextLine支持placeholder

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#484]
似乎早应该支持了……

@beidoufe 这边的需要

**Comment by yankun01** [comment]
3.2-dev分支已经支持。

**Comment by Justineo** [comment]
现在 3.2 的功能更新会同步到 3.1 不？

**Comment by otakustay** [comment]
这类简单的东西就同步过去吧？改动比较大的我想就不同步了

Best regards

Gray Zhang

在 2015年7月22日 下午12:17:43, Yiling GU (notifications@github.com) 写到:

现在 3.2 的功能更新会同步到 3.1 不？
