### ISSUE TITLE
问个问题，esui控件能和业务相关吗？

### ISSUE THREAD

**Issue by uraincay** [ecomfe/esui#491]
还是只能是非业务的公共视图的抽象。

**Comment by otakustay** [comment]
> esui项目里的控件能和业务相关吗

不能，现在唯一略和业务相关的是`Schedule`，更多是一种错误

> 继承自esui提供的class的控件能和业务相关吗

能，只要不在esui这个仓库里，你随意

**Comment by uraincay** [comment]
我想问的是项目里写的控件最好是那种形式：
类似esui库的和业务无关的公共控件
or
某些控件也是可以是和业务相关的

**Comment by otakustay** [comment]
如上面说的第2点，项目中的由开发者自己决定，可以是业务相关的，不受限制，我们也鼓励将一部分业务封装为控件来复用

**Comment by uraincay** [comment]
明白，谢谢神速解答。
