### ISSUE TITLE
TextLine疑似bug？

### ISSUE THREAD

**Issue by acelan86** [ecomfe/esui#493]
场景是这样的，textline被放在了一个dialog上，dialog未显示出来的时候初始化textline，会调用resetScroll方法，这时候textarea.clientHeight = 0, 导致了第一次初始化的行号容器高度为0，行号不显示

``` javascript
          resetScroll: function () {
                var textArea = this.helper.getPart('text');
                var lineNumber = this.helper.getPart('num-line');
                // 因为可能产生滚动条，所以要同步一下行码区和文字区的高度
                lineNumber.style.height = textArea.clientHeight + 'px';
                lineNumber.scrollTop = textArea.scrollTop;
            }
```

但是可以通过显示dialog后再初始化或者显示dialog后调用下resetScroll方法解决，是否有更好的方案？

**Comment by otakustay** [comment]
几乎所有依赖`offsetXxx`或者`clientXxx`的东西都会有这问题，除`TextLine`外还有`TextBox`、`Table`、`Button`，这个问题并无法在控件封装内部解决，在`MutationObserver`没法放心用的现状下也很难自动化，建议还是如主题中所说的自行调用相关方法处理一下吧

**Comment by acelan86** [comment]
谢～
