### ISSUE TITLE
是否有必要对table的每一行数据做容错处理？

### ISSUE THREAD

**Issue by acelan86** [ecomfe/esui#502]
当我的数据是这样的，假设他是因为数据库某种情况下某条数据外联id错误导致

``` json
{
    result: [
        null,  //错误数据
       {name: 'acelan'}
    ]
}
```

这时候table在渲染行数据的时候会报错

``` javascript
#1342 从这里进去当item为null的时候在调用content.call的时候就跪了
            for (var i = 0; i < dataLen; i++) {
                var item = data[i];
                html.push(getRowHtml(table, item, i, rowBuilderList));
            }
```

改成这样

``` javascript
           for (var i = 0; i < dataLen; i++) {
                var item = data[i];
                item && html.push(getRowHtml(table, item, i, rowBuilderList));  //或者更严谨点判断是个obj，然后抛出个警告之类的
            }
```

**Comment by yankun01** [comment]
其实加一个判断没啥问题。 数据会无缘无故少一条，是不是和pager啥都对应不起来了。最好还是把数据搞定吧。

**Comment by acelan86** [comment]
你永远不可能知道数据什么时候有问题，而且假设是脏数据，这样的话会导致报错后用户什么都操作不了，而且这只是一条数据的问题。。
然后这条脏数据你一天没找到，用户就一天不能干活。。

**Comment by otakustay** [comment]
为何不是你把数据给Table前就自己处理好呢

Best regards

Gray Zhang

在 2015年7月23日 上午11:33:15, acelan86 (notifications@github.com) 写到:

当我的数据是这样的，假设他是因为数据库某种情况下某条数据外联id错误导致

{
    result: [
        null,  //错误数据
       {name: 'acelan'}
    ]
}
这时候table在渲染行数据的时候会报错

#1342 从这里进去当item为null的时候在调用content.call的时候就跪了
            for (var i = 0; i < dataLen; i++) {
                var item = data[i];
                html.push(getRowHtml(table, item, i, rowBuilderList));
            }
改成这样

```
       for (var i = 0; i < dataLen; i++) {
            var item = data[i];
            item && html.push(getRowHtml(table, item, i, rowBuilderList));  //或者更严谨点判断是个obj，然后抛出个警告之类的
        }
```

**Comment by acelan86** [comment]
意思是每次我给table数据前都要自己过滤一遍？那为啥不放到公共的部分。。。

**Comment by otakustay** [comment]
数据处理是数据层面上的事，不是视图层面上的事。看一下后端经典的三层架构，校验和默认数据的填充从来不是DAO层甚至ORM层的事，肯定放在Service层来做
你的数据可能今天是给Table的，明天是给啥DataGrid的，后天发现数据少了就随便用个XxxList输出了，预先完成处理让数据本身的适用性更广更健壮

Best regards

Gray Zhang

在 2015年7月23日 上午11:43:46, acelan86 (notifications@github.com) 写到:

意思是每次我给table数据前都要自己过滤一遍？那为啥不放到公共的部分。。。
