### ISSUE TITLE
TableSubrow可以同时展开两个子行吗？

### ISSUE THREAD

**Issue by jiushiwoyuze** [ecomfe/esui#524]
请问，TableSubrow可以支持同时展开两个或更多子行吗？

**Comment by yankun01** [comment]
目前好像不行。在打开新的行的时候要关闭前面一行。

**Comment by yankun01** [comment]
@jiushiwoyuze 
https://github.com/ecomfe/esui/commit/f1988565d54943d2d84028be6111589dae622d58
fixed
