### ISSUE TITLE
toggle 应当支持传参数

### ISSUE THREAD

**Issue by Justineo** [ecomfe/esui#525]
改成这样：

``` js
// ...
toggle: function (isShow) {
    isShow = typeof isShow !== 'undefined' ? isShow : !this.isHidden();
    this[isShow ? 'hide' : 'show']();
},
// ...
```

这样这种经常出现的情况就可以避免了：

``` js
if (condition) {
    control.show();
}
else {
    control.hide();
}
```

不知道现在 PR 发到哪，先就写这里吧。

**Comment by yankun01** [comment]
@Justineo 这个是control类的toggle方法吗。 但是toggle的意思好像就是改变原来的状态的。加个参数为了让覆盖现有状态？

**Comment by otakustay** [comment]
同楼上，我觉得你需要的是个setVisibility方法？

**Comment by Justineo** [comment]
jQuery 的 toggle 可以传 boolean 参数表示需要隐藏还是显示。
http://api.jquery.com/toggle/#toggle-display

逻辑是传 boolean 根据参数来，不传的话切换状态。当然 `toggle` 和 `setVisibility` 分离也没问题。

**Comment by otakustay** [comment]
jQuery的所有API特点是把read和write整合在一个方法中，这和ESUI在“哲学”层面上不同

@yankun01 我建议加一个`setVisibility`方法，你要是觉得OK我可以给PR

**Comment by Justineo** [comment]
手滑了

**Comment by yankun01** [comment]
@otakustay 个人感觉加一个setVisibility会有些奇怪。要么就随了@Justineo的意思吧。加个参数表示toggle的意图。貌似也说的过去。

**Comment by otakustay** [comment]
奇怪在哪里呢……

**Comment by yankun01** [comment]
hide和show，toggle外加一个setVisibility。感觉方法有点多。

**Comment by otakustay** [comment]
如果API是各司其职的话，数量不是决定一个API有还是没有的原因吧

对于使用者，理解`toggle`+`setVisibility`和理解`toggle()`+`toggle(boolean)`的成本会有区别么……

再回头看react等框架与早期的jQuery、Sencha等比较，我感觉越是新出来的框架，在API上越是追求通过名字区别重载而不是通过参数来区别，这让所有的API更加expressive

比如react会分为`setState`、`replaceState`、`forceUpdate`，而不是在`setState`里加一个`{boolean} replace`和`{boolean} force`参数

甚至官方的`Map`方法也是`delete(key)`和`clear()`分为两个方法，不会出现“`delete`不传参数就是`clear`”这样的情况，同样也不会出现“`set`不传第2个参数就等于`delete`”这样的情况

总的来说，我认为随着JavaScript越来越偏向一个工程师的语言，API会更倾向于职责明确功能粒度细的设计
