### ISSUE TITLE
Region控件不支持更新regionData吗？

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/esui#538]
比如我现在有需求要根据不同的投放时间段和词包，显示当前可投放的地域。这时候我需要即时改变Region控件的数据，但貌似控件不支持？

**Comment by otakustay** [comment]
是的，地域数据是初始化决定的，这种场景建议你选择销毁旧的建个新的并同步选中项的方式进行

**Comment by feibinyang** [comment]
哦，好的。谢谢解答。
