### ISSUE TITLE
Select控件当更新数据源datasource时，没有触发change事件

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/esui#540]
我在使用Select控件的时候，发现当更新datasource时，如果selectedIndex值前后没有变化（比如更新之前selectedIndex值为0，更新datasource后默认selectedIndex也为0），此时不会触发change事件，这样就会导致跟Select控件绑定的change事件函数无法执行，产生bug。  
比如如下页面：当我选择行业时，就需要请求并刷新词包列表数据，但是词包列表更新完数据后却不触发change事件，导致无法更新关键词。产生bug。

![5e64d94eb1ace2d29324c5373e6f01af](https://cloud.githubusercontent.com/assets/2435478/11623267/c22f8fd0-9d06-11e5-8941-d1ffbe3d2197.png)

**Comment by otakustay** [comment]
变更`datasource`应该一定是由程序代码进行的，那么之后自行手动调用相关的更新逻辑即可

我们已经有不少Issue表明由程序修改属性触发`change`是不合理的（包括`.setValue`），因此不再继续添加这种不合理的实现了

**Comment by Justineo** [comment]
主要是变更 `datasource` 可能会使得 `selectedIndex` 发生变化，然后这时候会触发 `change`……不变时则不触发……
结果是变更 `datasource` 有时候抛事件，有时候不抛……

**Comment by otakustay** [comment]
是的，确实存在这一问题，这同样是因为对`selectedIndex`及`value`的修改会引发`change`导致的，但我觉得不能因为这个我们再在不对的路上走一步了……
