### ISSUE TITLE
关于lib/lang中克隆方法问题

### ISSUE THREAD

**Issue by xingzhewj** [ecomfe/esui#549]
1、https://github.com/ecomfe/esui/blob/master/src/lib/lang.js#L66
     此处对于数组采用underscore的clone方法，但是underscore的clone对于数组是直接用slice方式进行的      克隆，这是数组的浅克隆，对于数组中项为对象的情况会存在问题。
    而且lang中的deepClone与clone为同一方法，这样感觉不太好！

**Comment by otakustay** [comment]
我都不知道master是啥版本了，基本没在用
- https://github.com/ecomfe/esui/blob/3.1.0-dev/src/lib/lang.js
- https://github.com/ecomfe/esui/blob/3.2/develop/src/lib/lang.js

两个活跃分支都有修正这一问题

**Comment by Justineo** [comment]
@otakustay 路径给错了，分支名字改过了吧。
