### ISSUE TITLE
Layer第一次展示定位不准

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#550]
在Chrome下可以复现，符合以下条件：
1. 带Layer的控件（如`Calendar`）放在一个可滚动的容器（非`window`）内
2. 容器有一定的滚动（`offsetTop`）
3. 打开控件的Layer

定位会偏移容器的`scrollTop`值，从代码上来看`behavior/position`中的`getWithinInfo`并没有拿到正确的`offsetParent`，而是获取了`window`的滚动值（为0）

看上去这个定位的逻辑无法解决容器有滚动，甚至容器是`fixed`定位同时`window`和容器都有滚动的场景

由于`position`函数在实现时没有很好的拆分，代码量大太过复杂，缺少一些注释我也不知道各个变量代表啥，无处下手进行修改，还请协助修复一下

**Comment by yankun01** [comment]
@otakustay dev-3.2 分支已经修改
试一下。

**Comment by curarchy** [comment]
有效
