### ISSUE TITLE
做一个更轻量的Table

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#552]
针对性能到位的浏览器，基本实现以下功能：
1. 可指定某些列固定宽
2. 剩余列交给`<table>`原生元素自己算（即不再一行一个`<div>`了）
3. 可配置列的“可排序”性，可触发`sort`事件
4. 可实现行的多选、单选，可触发`select`事件，点击范围可控制全行或者仅`checkbox`
5. 单元格（表头、表身）可支持`string`、`html`、`ui`三种格式，分别对应纯字符串（自动编码）、HTML串、带控件的HTML串（加`init`），在`fields`中配置（表头、表身会分开）
6. 可通过扩展实现`subrow`（或更抽象的操作）及`inlineEdit`功能
7. 可以单独更新某一行的数据
8. 可以更改列配置（会造成完整重刷，不保留已选？）
9. 无数据时显示一定的HTML
10. 可配置单元格内容换行与否（`fields` 中配置）

移除的功能：
1. 列宽拖拽修改
2. 复杂的列宽计算
3. 配置`Tip`（改为表头单元格直接支持`ui`类型的内容）

我们需要重点讨论对`subrow`和`inlineEdit`进行支持的API设计

**Comment by otakustay** [comment]
待补充：控件属性定义

**Comment by otakustay** [comment]
待补充：`fields`格式定义

**Comment by otakustay** [comment]
待补充：针对扩展的API设计

**Comment by Phinome** [comment]
灰大，你埋了这么多伏笔额

**Comment by otakustay** [comment]
除了扩展性，功能都在 https://github.com/ecomfe/esui-light-table 实现了，后面我开始补文档，扩展性放最后考虑

当然IE8的兼容性被我扔天上去了- -

**Comment by otakustay** [comment]
之后有啥需求都在  https://github.com/ecomfe/esui-light-table 讨论即可
