### ISSUE TITLE
日程投放控件

### ISSUE THREAD

**Issue by gao5712975** [ecomfe/esui#564]
移动到有时间显示的遮罩层的时候再移出控件范围 ，有时间显示的遮罩层将不会显示。

**Comment by yankun01** [comment]
是3.1版本的吗，这是个bug。从格子移除到外面的时候没有触发事件。

**Comment by xutingting02** [comment]
这个问题3.1版本已经修复了，更新下代码再试试。
https://github.com/ecomfe/esui/commit/b3aace8ba34d32a2472c1fa8609fe329a97f1347

**Comment by gao5712975** [comment]
我没有用3.1版本的 我直接用的是master分支上面的代码，我自己改了，谢谢！

**Comment by yankun01** [comment]
如果是3.1分支，你用一下3.1/dev分支的。 
这个应该是新的。
