### ISSUE TITLE
Table 的 overflowX 属性为非 hidden 的时候多出一个横向滚动条

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/esui#569]
如图，上面那个滚动条是多余的：
![image](https://cloud.githubusercontent.com/assets/2581682/15346461/f9bec42a-1cea-11e6-8e76-860a55a14271.png)

经过代码查找，发现在 css 中对 <table> 设置了一个右侧的 border 宽度：
![image](https://cloud.githubusercontent.com/assets/2581682/15346487/3927337c-1ceb-11e6-9edb-c0dacd4eaa43.png)

但是在 Table 控件中计算 body 宽度的时候并未将这 1px 宽度考虑进去：
![image](https://cloud.githubusercontent.com/assets/2581682/15346509/618dacce-1ceb-11e6-9128-c60fb78da845.png)

**Comment by yankun01** [comment]
3.1版本吗？

**Comment by yibuyisheng** [comment]
是的。

**Comment by yankun01** [comment]
你都解决了。发个pr吧:p
