### ISSUE TITLE
对于带有数据源的控件是否应该支持外部不提供数据源的场景的表决

### ISSUE THREAD

**Issue by otakustay** [ecomfe/esui#599]
这是一个相对比较狭义的Case，但其隐含着设计组件时的思路，在这里仅以这个Case供大家作表决

场景是：带有数据源（`datasource`）的控件（`Select`、`Table`、`Tree`、`BoxGroup`、`CommandMenu`、`Tab`等），是否应该在外部不提供`datasource`时能正常渲染

此处的不提供是指在`render`开始时依旧没有提供，即我们肯定会支持`new`或`create`时不提供，后续通过`set`提供，再进行`render()`

**Comment by otakustay** [comment]
## 观点：不应该
1. `datasource`是控件渲染的核心参考，并不是像“文本框的后缀”那样可有可无的东西
2. 如果“数据源为空”，则应该提供`[]`或`{}`作为数据源，而不是不提供
3. 不提供`datasource`但需要这个控件就地渲染，这在业务上和逻辑上是说不通的
4. 未提供`datasource`很有可能是编程上的错误导致的（比如写成了`datasoruce`，或者绑定时对应的属性错误，或者某个后端接口调用失败了），从异常处理的角度来说应该尽早地抛出错误让业务逻辑知晓

“应该”的观点请 @bobshen 提供

**Comment by bobshen** [comment]
## 观点：应该
1. `esui` 提供的控件初始化方式并非只有通过JS脚本先 `create`再`set`再`render`这一种。考虑到使用场景，很大部分情况下开发者使用esui控件是通过模板声明的初始化方式。`main.js` 提供的`init`方法就是提供了这样一个功能。如果既不强制要求初始化的必要属性，又强制要求render前必要属性，会导致这个方法的字面意思、使用场景出现无法满足需求的情况。
2. 同意 `datasource` 在控件渲染过程的必要性。但是这并非要求 `datasource` 在 `render` 前必须由 **外部指定** 的理由
3. 在控件初始化阶段，`default options` 是一个通用的设置控件默认属性的方案。如果“数据源为空”，控件本身的 `default options.datasource` 可以作为后续渲染使用的数据，同时它的默认结构应该保证控件行为能够正常，这个是控件本身应该做好的事情。
4. 对于默认属性，也不只是 `datasource` 这个属性在 `selectors` 类控件中是必须存在的，还有一些其他属性对于其他类型的控件的渲染过程也是必要的。默认属性本身没有区分业务必要和业务非必要的差异。如果从设计上认为 `datasource` 在初始化阶段不设置会导致逻辑没有意义的话，那么其他的类似属性同样存在这些问题。这些将原本存在的数据结构从控件中抽离的行为是无法向后兼容的。

**Comment by errorrik** [comment]
应用程序的开发者（就是控件使用者）应该维护好自己的应用程序状态数据，在开始时就给出初始值，以此渲染控件。

但是站在控件开发者角度，谁知道控件使用者是否足够清醒呢？所以我投`应该`

**Comment by yibuyisheng** [comment]
这个问题感觉就是“传参”的问题：哪些参数是必传的，哪些参数是可选的。

个人拙见：我们不应该去说某个属性就应该是必须的，应该说某个控件的某个属性是不是必须的。为了降低 esui 使用门槛，避免错误，这种必须性和可选性信息必须要让使用者快速地获取到（注释清楚，或者所有可传入的属性集中写在一个地方），并且在运行时尽量提供一些机制去检测，可参考 React 的设计：

``` js
@params({
    datasource: arrayOf(Object).required,
    age: Integer,
    name: String.required
})
class SomeControl extends Control {
    // some code
}
```

**Comment by chestnutchen** [comment]
`应该`
同意 @bobshen 的观点

**Comment by otakustay** [comment]
@yibuyisheng 实际我们想讨论的是`datasource`是否应该设为`required`

**Comment by liuxuanzy** [comment]
``` html
<select></select>
```

**Comment by otakustay** [comment]
@liuxuanzy 考虑到HTMLElement.children不会是undefined/null，所以还是希望你能提供一个明确的结论，我们来参考

**Comment by liuxuanzy** [comment]
我觉得应当在组件初始化的时候处理datasource，允许不传递，不传递和传递空值等效。有时候写datasource:[]是比较没意思的事。

**Comment by yibuyisheng** [comment]
# 观点：应该

@otakustay 如果是针对于此处列举的场景（这些控件）的话，再结合平时实际使用 Table 的体验来讲，应该可以不用事先指定 datasource 。

赞同 @bobshen 在此场景下的观点。

**Comment by Justineo** [comment]
不太理解为啥要把「数据源」作为单独的属性来处理呢？是想突出不传此类属性时一定是本身业务逻辑发生了错误？事实上我们除了一些控件有一个重名的 `datasource` 属性以外，似乎没有对这个属性有任何特殊的处理吧。

**Comment by otakustay** [comment]
部分控件有默认值处理，部分没有

取数据源为例是因为它和TextBox的hint这种不同，被我理解为要使控件有意义就应该存在的东西，其他类似于Tabele的fields也是此类

GU Yiling notifications@github.com于2016年7月11日 周一下午2:12写道：

**Comment by Justineo** [comment]
所以这个话题其实不是 `datasource` 本身的问题，而是我们是否要在 ESUI 中引入 required properties 的问题咯？

**Comment by otakustay** [comment]
没错，我也刚想到，我们是不是应该做到“没有给定任何属性的情况下控件可正常运作”，对于这一点我持保留态度，至少react和ng2都没有这个要求

GU Yiling notifications@github.com于2016年7月11日 周一下午2:27写道：

**Comment by Justineo** [comment]
那就是我们要在代码逻辑中给出属性的元数据了，之前是没有的。

**Comment by otakustay** [comment]
我确实有给esui加propTypes的想法……

GU Yiling notifications@github.com于2016年7月11日 周一下午2:31写道：

**Comment by jinzhubaofu** [comment]
我怎么觉得这是一个『我们要不要提供默认值』的问题。

> 实际我们想讨论的是datasource是否应该设为 required

`datasource` 一定是 `isRequired`。也就是说一定不能是 `undefined` 或者是 `null`。进一步更严格要求，我们应该提供整个 datasource 可数据结构：

``` js
{
  datasource: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      value: PropTypes.string.isRequired
    })
  ).isRequired
}
```

不符合结构要求的都会得到 WARNING：

``` js
// 非法属性
null;
undefined;
['a', 'b', 'c'];
[{name: 111}];
[{name:  'aaa'}];

// 合法
[]
[{name: 'aaa', value: 'aaa'}]
```

在 `create` 时，用户不提供 datasource 则 defaults.datasource 可以替补出场；因此组件是有 datasource 的。只要默认值是合法的，也就是 OK 的。

在 `set` 时，此时 defaults 不能替补出场。如果 datasource 设定非法数据时都应该得到 WARNING；

所以我觉得在 render 前能够对属性进行结构校验是关键点。

基于以上，那么问题就变成了：要不要提供默认值。

如果把属性按重要程度分为两种：
1. 核心类，比如 Table 的 fields ；如果 Table 没有 fields 字段，那么 Table 就没有意义；并且我们不应该给 Table 提供默认的 fields，我们也没办法预测用户的意图来提供这样一个默认值。
2. 非核心类：Table  的 datasource 在逻辑上是允许为『空』的，感觉上并不是 core 字段，可以提供默认值 `[]`，应该是与 TextBox 的 placeholder 是一样的存在。

因此，个人觉得灰大说的有道理。核心类属性不提供默认值，如果用户不提供直接 throw 或者明显的 WARNING。非核心类建议提供默认值。

**Comment by Justineo** [comment]
哈哈，所以最后还是走 `PropTypes` 嘛。走统一的处理流程肯定控件单独去按「约定」做处理靠谱多了……

**Comment by otakustay** [comment]
考虑到现在这个表决的情况，以及参与表决的同学都有足够深厚的技术能力，我们会采取 @bobshen 的观点，补充到现有控件的实现中去

至于`propTypes`校验等，后续我会尽力跟进
